spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://192.168.99.100/dbdemo'
    username: root
    password: my-secret-pw
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
liquibase:
  change-log: 'classpath:changelog.xml'
  enabled: true